#!/bin/bash
# Satellite data download helper for Rhône river

echo "Rhône River Satellite Data Download"
echo "==================================="
echo ""
echo "Recommended downloads:"
echo ""
echo "1. Sentinel-2 (ESA Copernicus):"
echo "   - Go to: https://scihub.copernicus.eu/dhus/"
echo "   - Search: Sion, Switzerland"
echo "   - Filter: S2MSI1C, <20% cloud"
echo "   - Download: Latest scene"
echo ""
echo "2. Landsat 8/9 (USGS):"
echo "   - Go to: https://earthexplorer.usgs.gov/"
echo "   - Coordinates: 46.25°N, 7.40°E"
echo "   - Path/Row: 195/028"
echo "   - Collection: Landsat C2 L1"
echo ""
echo "3. After download:"
echo "   - Extract files to data/satellite/"
echo "   - Run load_satellite_image() function"
echo ""
